name:                glados
version:             0.1.0.0
github:              "githubuser/glados"
license:             BSD3
author:              "BEBOUUUUUUU"
maintainer:          "example@example.com"
copyright:           "2023 BEBOUUUUUUU"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/glados#readme>

dependencies:
- base >= 4.7 && < 5
- HUnit
- containers >= 0.6.2.1
- array >= 0.5.4.0
- binary >= 0.8.8.0
- bytestring >= 0.10.12.0
- cmdargs >= 0.10.21
# - data-elf >= 0.2
# - elf >= 0.31
- prettyprinter >= 1.7.0
- melf >= 1.3.0
- exceptions >= 0.10.4
- mtl >= 2.2.2
- process >= 1.6.9.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  # source-dirs: src/examples

executables:
  glados-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - glados

tests:
  glados-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - glados
