<token> ::= <symbol>
          | <integer>
          | <operator>
          | <keyword>
          | <comment>
          | <paren>
          | <error>
          | <whitespace>
          | <newline>
          | <bool>
          | <comparison>
          | <print>
          | <bracket>
          | <curly_bracket>
          | <type>
          | <deref>
          | <cast>

<symbol> ::= <letter>+

<integer> ::= <digit>+

<operator> ::= "+"
             | "add"
             | "-"
             | "sub"
             | "*"
             | "mul"
             | "/"
             | "div"
             | "%"
             | "//"
             | "="
             | ";"
             | "::"
             | "<"
             | "<="
             | ">"
             | ">="
             | "!="

<keyword> ::= "define"
            | "lambda"
            | "if"
            | "then"
            | "else"
            | "elif"
            | "eq?"
            | "mutable"
            | "while"
            | "for"
            | "as"

<comment> ::= "#" <text>

<paren> ::= "(" | ")"

<error> ::= <other>

<whitespace> ::= " "

<newline> ::= "\n"

<bool> ::= "true" | "false" | "#t" | "#f"

<comparison> ::= "<" | "<=" | ">" | ">=" | "eq?" | "!="

<print> ::= "print"

<bracket> ::= "[" | "]"

<curly_bracket> ::= "{" | "}"

<type> ::= "int" | "bool" | "float" | "@"

<deref> ::= "::"

<cast> ::= "as"

<digit> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"

<letter> ::= [a-z]

<semicolon> ::= ";"

<expression> ::= <integer>
            | <bool>
            | <symbol>
            | <symbol_declaration>

<symbol_declaration> ::= <type> <symbol> <semicolon>

<text> ::= <letter>+

<other> ::= <token>

<list> ::= "[" <expression>+ "]"

<func> ::= <type> <text> "(" <arg_list> ")" "{" <statement_list> "}"

<arg_list> ::= <argument> | <argument> "," <arg_list>
<argument> ::= <type> " " <text>

<statement_list> ::= <statement> | <statement> <statement_list>
<statement> ::= <expression_statement> | <if_statement> | <for_statement> | <jmp_statment>

<expression_statement> ::= <expression> ";"

<if_statement> ::= "if" "(" <expression> ")" "{" <statement_list> "}" <elif_statement> <else_statement>
<elif_statement> ::= "elif" "(" <expression> ")" "{" <statement_list> "}" <elif_statement> | " "
<else_statement> ::= "else" "{" <statement_list> "}" | " "

<for_statement> ::= "for" "(" <expression_statement> <expression> ";" <expression> ")" "{" <statement_list> "}"

<jmp_statment> ::= "continue" ";" | "break" ";" | <return_statement>

<return_statement> ::= "return" <expression> ";"

<binary_expression> ::= <expression> <operator> <expression>

<mutable> ::= <type> " " <text> " = " <expression>

<lambda> ::= "(" <text> ") => {" <statement_list> "}"

<func_call> ::= <text> "(" <arg_list> ")"

<set_mutable> ::= <symbol> "=" <expression> <semicolon>
<inc_mutable> ::= <symbol> "++" <semicolon>
<dec_mutable> ::= <symbol> "--" <semicolon>

<def_of_var> ::= <type> " " <text> <semicolon> "\n"

<struct> ::= "struct " <text> " = " "{\n" <def_of_var>+ "}"

<struct_val> ::= <text> "." <text>




exemple:
https://bnfplayground.pauliankline.com/?bnf=%0A%3Cdef_of_var%3E%20%3A%3A%3D%20%3Ctype%3E%20%22%20%22%20%3Ctext%3E%20%3Csemicolon%3E%20%22%5Cn%22%0A%0A%3Cstruct%3E%20%3A%3A%3D%20%22struct%20%22%20%3Ctext%3E%20%22%20%3D%20%22%20%22%7B%5Cn%22%20%3Cdef_of_var%3E%2B%20%22%7D%22%0A%0A%3Cstruct_val%3E%20%3A%3A%3D%20%3Ctext%3E%20%22.%22%20%3Ctext%3E%0A%3Ctype%3E%20%3A%3A%3D%20%22int%22%20%7C%20%22bool%22%20%7C%20%22float%22%20%7C%20%22%40%22%0A%3Csemicolon%3E%20%3A%3A%3D%20%22%3B%22%0A%3Ctext%3E%20%3A%3A%3D%20%3Cletter%3E%2B%0A%3Cletter%3E%20%3A%3A%3D%20%5Ba-z%5D&name=
