name: Check main and prepare to push

on:
  push:
    branches:
      - dev
  schedule:
    - cron: '0 12,23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if 'main' branch exists
        run: |
          if git branch | grep -q 'main'; then
            echo "'main' branch exists."
          else
            echo "'main' branch does not exist."
            exit 1
          fi

      - name: Push to main
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git switch main
          git merge origin/dev
          git push origin main -f
