name: Check main and prepare to push

on:
  # push:
  #   branches:
  #     - dev
  schedule:
    - cron: '0 12,23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Haskell environment
        uses: actions/setup-haskell@v1
        with:
          ghc-version: '8.10.3'
          cabal-version: '3.2'
          enable-stack: true
          stack-version: 'latest'

      - name: Install GMP library
        run: |
          sudo apt-get update
          sudo apt-get install libgmp-dev -y

      - name: Build project
        run: |
          make

      - name: Check if a file exists
        run: |
          if [ -f "./glados" ]; then
            echo "Binary exists."
          else
            echo "Binary does not exist, check."
            exit 1  # Exit with a non-zero status code to indicate failure
          fi

      - name: Integration Tests
        run: |
          ./scripts/run-it-bash.sh

      - name: Delete binary
        run: |
          make fclean

      # - name: Check if 'main' branch exists
      #   run: |
      #     git branch
      #     if git branch | grep -q 'main'; then
      #       echo "'main' branch exists."
      #     else
      #       echo "'main' branch does not exist."
      #       exit 1
      #     fi

      - name: Push to main
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git switch main
          git merge origin/dev
          git push origin main -f
